### PR TITLE
MIPS merge request.

### PR DESCRIPTION
**Pull request by nihilus**

### CODE REVIEW

**Comment by yegord** [comment]
1. Is this a merge request for MIPS and Allegrex, or for MIPS only?
2. Could you rebase on the latest yegord/master and squash everything into one commit, so that all the crazy merges, duplicated commits, and old discussions go away?

**Comment by nihilus** [comment]
@yegord both Allegrex and MIPS - I'll try to do the rebase'ing... However I am not so skilled with git yet.

**Comment by yegord** [comment]
Something like:
```
git diff yegord/master nihilius/master > patch.diff
git checkout -b yegord_master yegord/master
git apply patch.diff
```

**Comment by yegord** [comment]
If it is for Allegrex too, we need tests for it too.

**Comment by yegord** [comment]
Currently the branch does not compile with MSVC 2010, and compiles with warnings with Clang, GCC, MSVC 2013. Should I set up regular builds of some branch at your repository and redirect buildbot output to some mailing list?

**Comment by nihilus** [comment]
@yegord it won't compile with MSVC 2010 because of complex C++11 lambda expression in the delayslot handling.

**Comment by yegord** [comment]
Then, one needs to rewrite these lambdas.
MSVC 2010 is usually okay with them, as long as you provide the return type manually.

**Comment by nihilus** [comment]
@yegord you should be able to cherry pick the last 4 commits.

**Comment by yegord** [comment]
Okay, by rebasing and squashing I meant producing something like this:
https://github.com/yegord/snowman/commit/c5e20c6c77b00a45eaae0b09475cd2de551042a9

You can copy this branch to yourself, update the merge request to include this and only this commit.
I guess, the next steps would be me reading the patch, and you (and/or hlide) adding at least one test (with correct output) for Allegrex, adding correct outputs for MIPS tests, making everything build without warnings under GCC, Clang, MSVC >= 2010.

**Pull request closed without merging**
