### PR TITLE
Snowman yegord/nihilus Branch Merge

### PR DESCRIPTION
**Pull request by TheClockworker**
I hope by opening this pull request the required features I need to continue working on my personal projects can be implemented in the main branch.

### CODE REVIEW

**Comment by RomanHargrave** [comment]
Can you please add more information about your changes?

**Comment by TheClockworker** [comment]
What changes do you want more information about specifically? This merge/pull request is between my mirror of nihilus' master branch and yegord's master branch of snowman.

**Comment by RomanHargrave** [comment]
Because it would be nice to have a distilled list of changes introduced by the merge, though I just realized that this isn't from your fork, but someone else's.

**Comment by TheClockworker** [comment]
Yeah, This fork was supposed to be merged into the main snowman a while ago but for some reason it wasn't. It is all referenced in this thread. ( https://github.com/yegord/snowman/issues/65 )

**Comment by yegord** [comment]
Well, if you want me to spend time reviewing and merging the changes, please spend time splitting the changes into multiple pull requests, one per feature or fix. Also, please get rid of fixup commits like "Fix rebase junk".

**Comment by TheClockworker** [comment]
Yeah, I should have seen that coming.... I'll take your advice and split this up into smaller pull requests. Thanks for responding to this.

**Pull request closed without merging**
